### PR TITLE
fix: my plants page refactor

### LINKED ISSUE #125: My Plants page refactor
### Task Summary (Optional)

- pop up for details on plant (just notes added for now since other fields do not have relevance )
- style updates to ensure responsiveness

### Task Steps

- [ ]  pop up for details on plant (just notes added for now since other fields do not have relevance )
- [ ] style updates to ensure responsiveness

### Additional Comments (Optional)

_No response_

### Issue requirements

- [x] I have assigned appropriate scope label (backend, frontend, db, misc etc.) to this issue.
- [x] I have added this issue to the relevent project.

### PR DESCRIPTION
**Pull request by Sanj3101**
## Pull Request Requirments

-   [x] There is a corrsponding issue for this PR and it is assigned to me.

## Because

- pop up for details on plant (just notes added for now since other fields do not have relevance )
- style updates to ensure responsiveness
- simple animation for modals

## This PR

- pop up for details on plant (just notes added for now since other fields do not have relevance )
- style updates to ensure responsiveness
- simple animation for modals
- updated desktop view for add plant form

## Screenshots (visual changes in client side)

localhost_5173_userHome (4)
localhost_5173_userHome (3)
localhost_5173_userHome (2)
localhost_5173_userHome (1)

## Issue

Closes #125

### CODE REVIEW

File: server/lib/telegram/bot.js [hunk 1]
```diff
@@ -3,7 +3,7 @@ import TelegramBot from 'node-telegram-bot-api';
 const token = process.env.TELEGRAM_BOT_TOKEN;
 //const chatId = ; // You can store per-user too if needed
 
-const bot = new TelegramBot(token, { polling: true });
+const bot = new TelegramBot(token, { polling: false });
```
Comment (GaneshS288) [inline server/lib/telegram/bot.js:6]: Why was this line changed
